# Generated by Django 4.2 on 2023-04-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WaitTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wait_time', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CurrentTime',
        ),
    ]
