# Generated by Django 4.2 on 2023-04-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notime', '0002_line_waittime_delete_currenttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waittime',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
