# Generated by Django 4.2 on 2023-04-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notime', '0003_alter_waittime_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waittime',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
